version: '3.5'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - 8888:80
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: lol
            MYSQL_USER: lol
            MYSQL_PASSWORD: noquiero
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 33069:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - 9000:80
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
